package com.subtlesight.domain;

import com.subtlesight.domain.Models.*;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.EnumSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class CoreDomainTest {
    @Test void canonicalUrlDropsTrackingSortsQueryAndIsIdempotent(){String value=CanonicalUrl.normalize("HTTPS://Example.COM:443/a/../b/?utm_source=x&z=2&a=1#fragment");assertThat(value).isEqualTo("https://example.com/b?a=1&z=2");assertThat(CanonicalUrl.normalize(value)).isEqualTo(value);}
    @Test void rejectsUnsafeSchemesAndInvalidSignalValues(){assertThatThrownBy(()->CanonicalUrl.normalize("file:///secret")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new SignalFeatures(2,0,0,0,0,0,0,0,0,0)).isInstanceOf(IllegalArgumentException.class);}
    @Test void hashingIsStable(){assertThat(Hashing.sha256("SubtleSight")).hasSize(64).isEqualTo(Hashing.sha256("SubtleSight"));}
    @Test void jobStateMachineAcceptsOnlyDeclaredTransitions(){JobStateMachine.requireTransition(JobStatus.QUEUED,JobStatus.RUNNING);JobStateMachine.requireTransition(JobStatus.RUNNING,JobStatus.COMPLETED);assertThatThrownBy(()->JobStateMachine.requireTransition(JobStatus.COMPLETED,JobStatus.RUNNING)).isInstanceOf(IllegalStateException.class);}
    @Test void researchStateMachineLoopsForGapsButTerminalStatesStayTerminal(){ResearchStateMachine.requireTransition(ResearchStatus.REFLECTING,ResearchStatus.SEARCHING);ResearchStateMachine.requireTransition(ResearchStatus.VERIFYING,ResearchStatus.COMPLETED);assertThatThrownBy(()->ResearchStateMachine.requireTransition(ResearchStatus.COMPLETED,ResearchStatus.SEARCHING)).isInstanceOf(IllegalStateException.class);}
    @Test void hardBudgetCanNeverBeExceeded(){var budget=new ResearchBudget(2,3,100,new BigDecimal("1.00"),60);var ledger=new BudgetLedger(budget);ledger.reserve(1,2,50,new BigDecimal("0.40"),20);assertThat(ledger.canReserve(1,1,50,new BigDecimal("0.60"),40)).isTrue();assertThat(ledger.canReserve(2,0,0,BigDecimal.ZERO,0)).isFalse();assertThatThrownBy(()->ledger.reserve(1,2,51,new BigDecimal("0.61"),41)).isInstanceOf(IllegalStateException.class);assertThat(ledger.usage().tokens()).isEqualTo(50);}
    @Test void recordContractsRejectInvalidBudgetsAndEvidenceBounds(){assertThatThrownBy(()->new ResearchBudget(0,1,1,BigDecimal.ONE,1)).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new Evidence(java.util.UUID.randomUUID(),java.util.UUID.randomUUID(),"q",2,1,"x","a".repeat(64),"f",EvidenceRelation.SUPPORTS,.5,java.time.Instant.now())).isInstanceOf(IllegalArgumentException.class);}
    @Test void everyJobTransitionIsEnforced(){Map<JobStatus,Set<JobStatus>> allowed=Map.of(JobStatus.QUEUED,EnumSet.of(JobStatus.RUNNING,JobStatus.PAUSED,JobStatus.CANCELLED),JobStatus.RUNNING,EnumSet.of(JobStatus.COMPLETED,JobStatus.RETRY_WAIT,JobStatus.FAILED,JobStatus.CANCELLED),JobStatus.RETRY_WAIT,EnumSet.of(JobStatus.QUEUED,JobStatus.CANCELLED,JobStatus.FAILED),JobStatus.PAUSED,EnumSet.of(JobStatus.QUEUED,JobStatus.CANCELLED),JobStatus.COMPLETED,Set.of(),JobStatus.FAILED,Set.of(),JobStatus.CANCELLED,Set.of());for(JobStatus from:JobStatus.values())for(JobStatus to:JobStatus.values())if(allowed.get(from).contains(to))JobStateMachine.requireTransition(from,to);else assertThatThrownBy(()->JobStateMachine.requireTransition(from,to)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->JobStateMachine.requireTransition(null,JobStatus.QUEUED)).isInstanceOf(IllegalStateException.class);}
    @Test void everyResearchTransitionIsEnforced(){Map<ResearchStatus,Set<ResearchStatus>> allowed=Map.ofEntries(Map.entry(ResearchStatus.CREATED,Set.of(ResearchStatus.SCOPING,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.SCOPING,Set.of(ResearchStatus.PLANNING,ResearchStatus.FAILED,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.PLANNING,Set.of(ResearchStatus.SEARCHING,ResearchStatus.FAILED,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.SEARCHING,Set.of(ResearchStatus.READING,ResearchStatus.PAUSED,ResearchStatus.PARTIAL,ResearchStatus.FAILED,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.READING,Set.of(ResearchStatus.EXTRACTING,ResearchStatus.PAUSED,ResearchStatus.PARTIAL,ResearchStatus.FAILED,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.EXTRACTING,Set.of(ResearchStatus.REFLECTING,ResearchStatus.PARTIAL,ResearchStatus.FAILED,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.REFLECTING,Set.of(ResearchStatus.SEARCHING,ResearchStatus.WRITING,ResearchStatus.PARTIAL,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.WRITING,Set.of(ResearchStatus.VERIFYING,ResearchStatus.PARTIAL,ResearchStatus.FAILED,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.VERIFYING,Set.of(ResearchStatus.SEARCHING,ResearchStatus.COMPLETED,ResearchStatus.PARTIAL,ResearchStatus.FAILED)),Map.entry(ResearchStatus.PAUSED,Set.of(ResearchStatus.SEARCHING,ResearchStatus.CANCELLED)),Map.entry(ResearchStatus.COMPLETED,Set.of()),Map.entry(ResearchStatus.PARTIAL,Set.of()),Map.entry(ResearchStatus.CANCELLED,Set.of()),Map.entry(ResearchStatus.FAILED,Set.of()));for(ResearchStatus from:ResearchStatus.values())for(ResearchStatus to:ResearchStatus.values())if(allowed.get(from).contains(to))ResearchStateMachine.requireTransition(from,to);else assertThatThrownBy(()->ResearchStateMachine.requireTransition(from,to)).isInstanceOf(IllegalStateException.class);}
    @Test void canonicalUrlCoversDefaultsPortsTrackingAndSyntax(){assertThat(CanonicalUrl.normalize("example.com")).isEqualTo("https://example.com/");assertThat(CanonicalUrl.normalize("http://EXAMPLE.com:80/path/?ref=x&utm_campaign=y")).isEqualTo("http://example.com/path");assertThat(CanonicalUrl.normalize("https://bücher.example/a?b=2&a=1")).contains("xn--bcher-kva.example").endsWith("?a=1&b=2");assertThatThrownBy(()->CanonicalUrl.normalize(" ")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->CanonicalUrl.normalize("http://[bad")).isInstanceOf(IllegalArgumentException.class);}
    @Test void budgetRejectsEveryNegativeDimensionAndEveryHardLimit(){ResearchBudget b=new ResearchBudget(1,1,1,BigDecimal.ONE,1);for(int dimension=0;dimension<5;dimension++){BudgetLedger l=new BudgetLedger(b);int d=dimension;assertThatThrownBy(()->l.reserve(d==0?-1:0,d==1?-1:0,d==2?-1:0,d==3?new BigDecimal("-1"):BigDecimal.ZERO,d==4?-1:0)).isInstanceOf(IllegalStateException.class);}assertThat(new BudgetLedger(b).canReserve(1,1,1,BigDecimal.ONE,1)).isTrue();assertThat(new BudgetLedger(b).canReserve(2,0,0,BigDecimal.ZERO,0)).isFalse();assertThat(new BudgetLedger(b).canReserve(0,2,0,BigDecimal.ZERO,0)).isFalse();assertThat(new BudgetLedger(b).canReserve(0,0,2,BigDecimal.ZERO,0)).isFalse();assertThat(new BudgetLedger(b).canReserve(0,0,0,new BigDecimal("2"),0)).isFalse();assertThat(new BudgetLedger(b).canReserve(0,0,0,BigDecimal.ZERO,2)).isFalse();}
    @Test void domainRecordsNormalizeNullableCollectionsAndRejectMissingIdentity(){Instant now=Instant.now();UUID id=UUID.randomUUID();Source source=new Source(id,"s",SourceType.RSS,SourceKind.PERSISTENT,"https://x.test",null,null,SourceTier.PRIMARY,SourceHealth.HEALTHY,null,true,1,now,now);assertThat(source.topics()).isEmpty();DocumentVersion doc=new DocumentVersion(id,id,"t",null,null,null,"https://x.test",null,"h","s","v",null,false,now);assertThat(doc.text()).isEmpty();assertThat(doc.language()).isEqualTo("und");SignalFeatures zero=new SignalFeatures(0,0,0,0,0,0,0,0,0,0);Signal signal=new Signal(id,id,ViewType.LATEST,null,zero,0,null,now);assertThat(signal.reasonCodes()).isEmpty();assertThat(new FeedItem(null,null,false,false,null).timeline()).isEmpty();assertThat(new AgentRequest("go",false,null).context()).isEmpty();assertThat(new AgentResponse("ok",null,null,false).tools()).isEmpty();assertThatThrownBy(()->new Source(null,"s",SourceType.RSS,SourceKind.PERSISTENT,"x",null,null,SourceTier.PRIMARY,SourceHealth.HEALTHY,Set.of(),true,1,now,now)).isInstanceOf(NullPointerException.class);assertThatThrownBy(()->new ResearchUsage(-1,0,0,BigDecimal.ZERO,0)).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new SignalFeatures(Double.NaN,0,0,0,0,0,0,0,0,0)).isInstanceOf(IllegalArgumentException.class);}
}
