import { Button, Card, Progress, Tag, Tooltip } from '@douyinfe/semi-ui';
import { IconBookmark, IconChevronRight, IconEyeClosed, IconSearch } from '@douyinfe/semi-icons';
import { useNavigate } from 'react-router-dom';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { post } from '../api/client';
import type { FeedItem } from '../types';

const reason:Record<string,string>={HIGH_IMPACT:'高影响',RAPID_GROWTH:'快速增长',MULTIPLE_INDEPENDENT_SOURCES:'多独立来源',SOURCE_DISAGREEMENT:'来源存在分歧',NOVEL_INFORMATION:'新颖信息',MATCHES_YOUR_INTERESTS:'匹配你的关注',RECENT_RELEVANT_UPDATE:'近期相关更新'};
export function StoryCard({item}:{item:FeedItem}){const navigate=useNavigate(),client=useQueryClient();const feedback=useMutation({mutationFn:(type:string)=>post(`/stories/${item.story.id}/feedback`,{type}),onSuccess:()=>client.invalidateQueries({queryKey:['feed']})});return <Card className="story-card" bodyStyle={{padding:0}}><div className="story-card-body"><div className="story-meta"><Tag color={item.story.sourceFamilyCount>2?'blue':'grey'}>{item.story.sourceFamilyCount} 个独立来源</Tag><span>{new Date(item.story.lastObservedAt).toLocaleString()}</span><span>置信度 {Math.round(item.signal.features.confidence*100)}%</span></div><h3 onClick={()=>navigate(`/stories/${item.story.id}`)}>{item.story.title}</h3><p>{item.story.summary||'已完成原文归档与事件聚合，等待进一步摘要增强。'}</p><div className="story-tags">{item.story.topics.slice(0,4).map(v=><Tag key={v}>{v}</Tag>)}{item.signal.reasonCodes.slice(0,3).map(v=><Tooltip key={v} content="由可重复的 Signal 特征计算"><Tag color="green">{reason[v]??v}</Tag></Tooltip>)}</div><div className="confidence"><span>Signal</span><Progress percent={Math.round(item.signal.score*100)} showInfo={false}/><b>{Math.round(item.signal.score*100)}</b></div></div><div className="story-actions"><Button theme="borderless" icon={<IconBookmark/>} onClick={()=>feedback.mutate('SAVE')}>{item.saved?'已保存':'保存'}</Button><Button theme="borderless" icon={<IconEyeClosed/>} onClick={()=>feedback.mutate('HIDE')}>隐藏</Button><Button theme="borderless" icon={<IconSearch/>} onClick={()=>navigate(`/research?story=${item.story.id}&q=${encodeURIComponent(item.story.title)}`)}>研究</Button><Button theme="borderless" icon={<IconChevronRight/>} onClick={()=>navigate(`/stories/${item.story.id}`)}>时间线</Button></div></Card>}

