import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Input, Modal, Select, Tag, Toast } from '@douyinfe/semi-ui';
import { IconDownload, IconPlus, IconSend } from '@douyinfe/semi-icons';
import { get, post } from '../api/client';
import type { ReportVersion, ResearchRun } from '../types';
import { PageHeader } from '../components/PageHeader';
import { StatePanel } from '../components/StatePanel';

export function ReportsPage(){const client=useQueryClient();const [modal,setModal]=useState(false),[researchId,setResearchId]=useState(''),[title,setTitle]=useState('SubtleSight 研究报告'),[type,setType]=useState('DEEP_RESEARCH'),[preview,setPreview]=useState<ReportVersion>();const reports=useQuery({queryKey:['reports'],queryFn:()=>get<ReportVersion[]>('/reports')});const research=useQuery({queryKey:['research'],queryFn:()=>get<ResearchRun[]>('/research')});const create=useMutation({mutationFn:()=>post<ReportVersion>('/reports',{researchId,type,title}),onSuccess:r=>{client.invalidateQueries({queryKey:['reports']});setPreview(r);setModal(false);Toast.success('报告快照已锁定')}});const download=(r:ReportVersion,format:string)=>{window.open(`/api/v1/reports/${r.id}/export/${format}`,'_blank')};return <><PageHeader eyebrow="REPORT & PUBLISH" title="报告" description="从锁定的 Claim/Evidence 快照渲染；引用未验证时禁止发布。" actions={<Button theme="solid" icon={<IconPlus/>} onClick={()=>setModal(true)}>生成报告</Button>}/><StatePanel loading={reports.isLoading} error={reports.error} empty={!reports.data?.length}><div className="report-grid">{reports.data?.map(r=><div key={r.id} onClick={()=>setPreview(r)}><Card className="report-card"><div className="report-cover"><span>SubtleSight</span><small>{r.reportType}</small></div><div className="report-body"><Tag color={r.citationsVerified?'green':'red'}>{r.citationsVerified?'引用已验证':'引用未通过'}</Tag><h3>{r.title}</h3><p>版本 v{r.version} · {new Date(r.createdAt).toLocaleString()}</p><div className="report-buttons">{['markdown','html','pdf','json'].map(f=><Button key={f} size="small" icon={<IconDownload/>} onClick={e=>{e.stopPropagation();download(r,f)}}>{f.toUpperCase()}</Button>)}</div></div></Card></div>)}</div></StatePanel><Modal visible={modal} title="从研究生成报告" onCancel={()=>setModal(false)} onOk={()=>create.mutate()} confirmLoading={create.isPending}><label className="field-label">研究任务</label><Select value={researchId} onChange={v=>setResearchId(String(v))} optionList={(research.data??[]).map(r=>({label:`${r.status} · ${r.question}`,value:r.id}))} style={{width:'100%'}}/><label className="field-label">报告类型</label><Select value={type} onChange={v=>setType(String(v))} optionList={['DAILY','WEEKLY','WATCHLIST_DELTA','DEEP_RESEARCH','INCIDENT_TIMELINE'].map(v=>({label:v,value:v}))} style={{width:'100%'}}/><label className="field-label">标题</label><Input value={title} onChange={setTitle}/></Modal><Modal visible={!!preview} title={preview?.title} onCancel={()=>setPreview(undefined)} footer={<><Button onClick={()=>setPreview(undefined)}>关闭</Button><Button theme="solid" icon={<IconSend/>} disabled={!preview?.citationsVerified}>发布</Button></>} width={800}><div className="report-preview" dangerouslySetInnerHTML={{__html:preview?.html??''}}/></Modal></>}
