import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Button, Card, Input, Modal, Progress, Select, Table, Tag, Timeline, Toast } from '@douyinfe/semi-ui';
import { IconPlus } from '@douyinfe/semi-icons';
import { get, post } from '../api/client';
import type { Claim, ResearchRun } from '../types';
import { PageHeader } from '../components/PageHeader';
import { StatePanel } from '../components/StatePanel';

type Detail={run:ResearchRun;claims:Claim[]};const stages=['CREATED','SCOPING','PLANNING','SEARCHING','READING','EXTRACTING','REFLECTING','WRITING','VERIFYING','COMPLETED'];
export function ResearchPage(){const {id}=useParams(),location=useLocation(),navigate=useNavigate();const preset=new URLSearchParams(location.search);const [modal,setModal]=useState(!!preset.get('q')),[question,setQuestion]=useState(preset.get('q')??''),[mode,setMode]=useState('STANDARD');const list=useQuery({queryKey:['research'],queryFn:()=>get<ResearchRun[]>('/research'),refetchInterval:3000,enabled:!id});const detail=useQuery({queryKey:['research',id],queryFn:()=>get<Detail>(`/research/${id}`),refetchInterval:q=>['COMPLETED','PARTIAL','FAILED','CANCELLED'].includes(q.state.data?.run.status??'')?false:2000,enabled:!!id});const start=useMutation({mutationFn:()=>post<ResearchRun>('/research',{storyId:preset.get('story')||null,question,mode}),onSuccess:r=>{setModal(false);navigate(`/research/${r.id}`);Toast.success('研究任务已进入持久化队列')}});if(id){const run=detail.data?.run;const stage=Math.max(0,stages.indexOf(run?.status??'CREATED'));return <StatePanel loading={detail.isLoading} error={detail.error}><PageHeader eyebrow="DEEP RESEARCH" title={run?.question??'研究'} description="状态、预算和证据均持续保存；中断后从最近检查点恢复。" actions={<Tag color={run?.status==='COMPLETED'?'green':run?.status==='PARTIAL'?'orange':'blue'} size="large">{run?.status}</Tag>}/><div className="research-progress"><Progress percent={Math.round(stage/(stages.length-1)*100)} showInfo/><div className="stage-row">{stages.slice(1,-1).map((s,i)=><span key={s} className={i<stage?'active':''}>{s}</span>)}</div></div><div className="detail-grid"><Card title="研究过程" className="panel-card"><Timeline>{stages.slice(0,Math.max(stage+1,1)).map(s=><Timeline.Item key={s} type={s===run?.status?'success':'default'}>{s}</Timeline.Item>)}</Timeline></Card><Card title="预算账本" className="panel-card"><div className="metric-list"><div><span>查询</span><b>{run?.usage.queries??0}</b></div><div><span>页面</span><b>{run?.usage.pages??0}</b></div><div><span>Token</span><b>{run?.usage.tokens??0}</b></div></div>{run?.gaps?.length?<><h4>明确缺口</h4>{run.gaps.map(g=><p className="gap" key={g}>{g}</p>)}</>:<p className="ok-copy">暂无未解决的关键缺口</p>}</Card></div><Card title="Claim / Evidence Matrix" className="panel-card table-card"><Table pagination={false} dataSource={detail.data?.claims} columns={[{title:'关键 Claim',dataIndex:'statement'},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='SUPPORTED'?'green':v==='DISPUTED'?'orange':'grey'}>{v}</Tag>},{title:'关键',dataIndex:'critical',render:v=>v?'是':'否'}]}/></Card></StatePanel>}
  return <><PageHeader eyebrow="RESEARCH RUNS" title="研究" description="Verify、Standard、Deep 与 Continuous 四种模式，共用可恢复研究状态机。" actions={<Button theme="solid" icon={<IconPlus/>} onClick={()=>setModal(true)}>新建研究</Button>}/><StatePanel loading={list.isLoading} error={list.error} empty={!list.data?.length}><div className="run-grid">{list.data?.map(run=><div key={run.id} onClick={()=>navigate(`/research/${run.id}`)}><Card className="run-card"><div className="run-head"><Tag>{run.mode}</Tag><Tag color={run.status==='COMPLETED'?'green':run.status==='PARTIAL'?'orange':'blue'}>{run.status}</Tag></div><h3>{run.question}</h3><p>{run.gaps?.[0]||'证据检索与验证进行中'}</p><small>{new Date(run.updatedAt).toLocaleString()}</small></Card></div>)}</div></StatePanel><Modal visible={modal} title="启动 DeepSearch" onCancel={()=>setModal(false)} onOk={()=>start.mutate()} confirmLoading={start.isPending}><label className="field-label">研究问题</label><Input value={question} onChange={setQuestion} placeholder="需要核实或深入回答的问题"/><label className="field-label">研究模式</label><Select value={mode} onChange={v=>setMode(String(v))} optionList={[{label:'Verify · 快速核实',value:'VERIFY'},{label:'Standard · 标准研究',value:'STANDARD'},{label:'Deep · 深度研究',value:'DEEP'},{label:'Continuous · 持续研究',value:'CONTINUOUS'}]} style={{width:'100%'}}/></Modal></>}
