import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Button, Card, Input, Modal, Progress, Select, Table, Tag, Timeline, Toast } from '@douyinfe/semi-ui';
import { IconPlus } from '@douyinfe/semi-icons';
import { get, post } from '../api/client';
import { PageHeader } from '../components/PageHeader';
import { StatePanel } from '../components/StatePanel';
const stages = ['CREATED', 'SCOPING', 'PLANNING', 'SEARCHING', 'READING', 'EXTRACTING', 'REFLECTING', 'WRITING', 'VERIFYING', 'COMPLETED'];
export function ResearchPage() {
    const { id } = useParams(), location = useLocation(), navigate = useNavigate();
    const preset = new URLSearchParams(location.search);
    const [modal, setModal] = useState(!!preset.get('q')), [question, setQuestion] = useState(preset.get('q') ?? ''), [mode, setMode] = useState('STANDARD');
    const list = useQuery({ queryKey: ['research'], queryFn: () => get('/research'), refetchInterval: 3000, enabled: !id });
    const detail = useQuery({ queryKey: ['research', id], queryFn: () => get(`/research/${id}`), refetchInterval: q => ['COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED'].includes(q.state.data?.run.status ?? '') ? false : 2000, enabled: !!id });
    const start = useMutation({ mutationFn: () => post('/research', { storyId: preset.get('story') || null, question, mode }), onSuccess: r => { setModal(false); navigate(`/research/${r.id}`); Toast.success('研究任务已进入持久化队列'); } });
    if (id) {
        const run = detail.data?.run;
        const stage = Math.max(0, stages.indexOf(run?.status ?? 'CREATED'));
        return _jsxs(StatePanel, { loading: detail.isLoading, error: detail.error, children: [_jsx(PageHeader, { eyebrow: "DEEP RESEARCH", title: run?.question ?? '研究', description: "\u72B6\u6001\u3001\u9884\u7B97\u548C\u8BC1\u636E\u5747\u6301\u7EED\u4FDD\u5B58\uFF1B\u4E2D\u65AD\u540E\u4ECE\u6700\u8FD1\u68C0\u67E5\u70B9\u6062\u590D\u3002", actions: _jsx(Tag, { color: run?.status === 'COMPLETED' ? 'green' : run?.status === 'PARTIAL' ? 'orange' : 'blue', size: "large", children: run?.status }) }), _jsxs("div", { className: "research-progress", children: [_jsx(Progress, { percent: Math.round(stage / (stages.length - 1) * 100), showInfo: true }), _jsx("div", { className: "stage-row", children: stages.slice(1, -1).map((s, i) => _jsx("span", { className: i < stage ? 'active' : '', children: s }, s)) })] }), _jsxs("div", { className: "detail-grid", children: [_jsx(Card, { title: "\u7814\u7A76\u8FC7\u7A0B", className: "panel-card", children: _jsx(Timeline, { children: stages.slice(0, Math.max(stage + 1, 1)).map(s => _jsx(Timeline.Item, { type: s === run?.status ? 'success' : 'default', children: s }, s)) }) }), _jsxs(Card, { title: "\u9884\u7B97\u8D26\u672C", className: "panel-card", children: [_jsxs("div", { className: "metric-list", children: [_jsxs("div", { children: [_jsx("span", { children: "\u67E5\u8BE2" }), _jsx("b", { children: run?.usage.queries ?? 0 })] }), _jsxs("div", { children: [_jsx("span", { children: "\u9875\u9762" }), _jsx("b", { children: run?.usage.pages ?? 0 })] }), _jsxs("div", { children: [_jsx("span", { children: "Token" }), _jsx("b", { children: run?.usage.tokens ?? 0 })] })] }), run?.gaps?.length ? _jsxs(_Fragment, { children: [_jsx("h4", { children: "\u660E\u786E\u7F3A\u53E3" }), run.gaps.map(g => _jsx("p", { className: "gap", children: g }, g))] }) : _jsx("p", { className: "ok-copy", children: "\u6682\u65E0\u672A\u89E3\u51B3\u7684\u5173\u952E\u7F3A\u53E3" })] })] }), _jsx(Card, { title: "Claim / Evidence Matrix", className: "panel-card table-card", children: _jsx(Table, { pagination: false, dataSource: detail.data?.claims, columns: [{ title: '关键 Claim', dataIndex: 'statement' }, { title: '状态', dataIndex: 'status', render: v => _jsx(Tag, { color: v === 'SUPPORTED' ? 'green' : v === 'DISPUTED' ? 'orange' : 'grey', children: v }) }, { title: '关键', dataIndex: 'critical', render: v => v ? '是' : '否' }] }) })] });
    }
    return _jsxs(_Fragment, { children: [_jsx(PageHeader, { eyebrow: "RESEARCH RUNS", title: "\u7814\u7A76", description: "Verify\u3001Standard\u3001Deep \u4E0E Continuous \u56DB\u79CD\u6A21\u5F0F\uFF0C\u5171\u7528\u53EF\u6062\u590D\u7814\u7A76\u72B6\u6001\u673A\u3002", actions: _jsx(Button, { theme: "solid", icon: _jsx(IconPlus, {}), onClick: () => setModal(true), children: "\u65B0\u5EFA\u7814\u7A76" }) }), _jsx(StatePanel, { loading: list.isLoading, error: list.error, empty: !list.data?.length, children: _jsx("div", { className: "run-grid", children: list.data?.map(run => _jsx("div", { onClick: () => navigate(`/research/${run.id}`), children: _jsxs(Card, { className: "run-card", children: [_jsxs("div", { className: "run-head", children: [_jsx(Tag, { children: run.mode }), _jsx(Tag, { color: run.status === 'COMPLETED' ? 'green' : run.status === 'PARTIAL' ? 'orange' : 'blue', children: run.status })] }), _jsx("h3", { children: run.question }), _jsx("p", { children: run.gaps?.[0] || '证据检索与验证进行中' }), _jsx("small", { children: new Date(run.updatedAt).toLocaleString() })] }) }, run.id)) }) }), _jsxs(Modal, { visible: modal, title: "\u542F\u52A8 DeepSearch", onCancel: () => setModal(false), onOk: () => start.mutate(), confirmLoading: start.isPending, children: [_jsx("label", { className: "field-label", children: "\u7814\u7A76\u95EE\u9898" }), _jsx(Input, { value: question, onChange: setQuestion, placeholder: "\u9700\u8981\u6838\u5B9E\u6216\u6DF1\u5165\u56DE\u7B54\u7684\u95EE\u9898" }), _jsx("label", { className: "field-label", children: "\u7814\u7A76\u6A21\u5F0F" }), _jsx(Select, { value: mode, onChange: v => setMode(String(v)), optionList: [{ label: 'Verify · 快速核实', value: 'VERIFY' }, { label: 'Standard · 标准研究', value: 'STANDARD' }, { label: 'Deep · 深度研究', value: 'DEEP' }, { label: 'Continuous · 持续研究', value: 'CONTINUOUS' }], style: { width: '100%' } })] })] });
}
