import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Card, List, Tag, Timeline } from '@douyinfe/semi-ui';
import { IconSearch } from '@douyinfe/semi-icons';
import { get } from '../api/client';
import { PageHeader } from '../components/PageHeader';
import { StatePanel } from '../components/StatePanel';
export function StoryPage() { const { id } = useParams(), navigate = useNavigate(); const list = useQuery({ queryKey: ['stories'], queryFn: () => get('/stories?limit=100'), enabled: !id }); const detail = useQuery({ queryKey: ['story', id], queryFn: () => get(`/stories/${id}`), enabled: !!id }); if (id)
    return _jsxs(StatePanel, { loading: detail.isLoading, error: detail.error, children: [_jsx(PageHeader, { eyebrow: "STORY TIMELINE", title: detail.data?.story.title ?? '事件', description: "\u5C06\u5B98\u65B9\u53D1\u5E03\u3001\u5A92\u4F53\u5206\u6790\u4E0E\u793E\u533A\u7EBF\u7D22\u653E\u56DE\u540C\u4E00\u4E8B\u4EF6\u8109\u7EDC\uFF0C\u540C\u65F6\u4FDD\u7559\u5176\u6765\u6E90\u89D2\u8272\u3002", actions: _jsx(Button, { theme: "solid", icon: _jsx(IconSearch, {}), onClick: () => navigate(`/research?story=${id}&q=${encodeURIComponent(detail.data?.story.title ?? '')}`), children: "\u542F\u52A8\u7814\u7A76" }) }), _jsxs("div", { className: "detail-grid", children: [_jsx(Card, { title: "\u4E8B\u4EF6\u8109\u7EDC", className: "panel-card", children: _jsx(Timeline, { children: detail.data?.timeline.map(m => _jsxs(Timeline.Item, { time: new Date(m.addedAt).toLocaleString(), type: m.role === 'PRIMARY' ? 'success' : 'default', children: [_jsx("strong", { children: m.role === 'PRIMARY' ? '一级来源' : '相关报道' }), _jsx("p", { children: m.sourceFamily }), _jsxs("small", { children: ["\u805A\u7C7B\u76F8\u4F3C\u5EA6 ", Math.round(m.similarity * 100), "%"] })] }, m.documentVersionId)) }) }), _jsxs(Card, { title: "\u60C5\u62A5\u753B\u50CF", className: "panel-card", children: [_jsxs("div", { className: "metric-list", children: [_jsxs("div", { children: [_jsx("span", { children: "\u6765\u6E90" }), _jsx("b", { children: detail.data?.story.sourceCount })] }), _jsxs("div", { children: [_jsx("span", { children: "\u72EC\u7ACB\u6765\u6E90\u65CF" }), _jsx("b", { children: detail.data?.story.sourceFamilyCount })] }), _jsxs("div", { children: [_jsx("span", { children: "\u4EBA\u5DE5\u8986\u76D6" }), _jsx("b", { children: detail.data?.story.manualOverride ? '是' : '否' })] })] }), _jsx("h4", { children: "\u5B9E\u4F53" }), detail.data?.story.entities.map(v => _jsx(Tag, { children: v }, v)), _jsx("h4", { children: "\u4E3B\u9898" }), detail.data?.story.topics.map(v => _jsx(Tag, { color: "blue", children: v }, v))] })] })] }); return _jsxs(_Fragment, { children: [_jsx(PageHeader, { eyebrow: "STORY GRAPH", title: "\u4E8B\u4EF6", description: "\u53BB\u91CD\u540E\u7684\u4E8B\u4EF6\u96C6\u5408\uFF0C\u800C\u4E0D\u662F\u91CD\u590D\u65B0\u95FB\u5217\u8868\u3002" }), _jsx(StatePanel, { loading: list.isLoading, error: list.error, empty: !list.data?.length, children: _jsx(List, { className: "list-panel", dataSource: list.data, renderItem: story => _jsx(List.Item, { onClick: () => navigate(`/stories/${story.id}`), main: _jsxs("div", { children: [_jsx("h3", { children: story.title }), _jsx("p", { children: story.summary || '等待摘要增强' })] }), extra: _jsxs("div", { children: [_jsxs(Tag, { children: [story.sourceFamilyCount, " \u6765\u6E90\u65CF"] }), _jsx("span", { children: new Date(story.lastObservedAt).toLocaleDateString() })] }) }) }) })] }); }
