import { useQuery } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Card, List, Tag, Timeline } from '@douyinfe/semi-ui';
import { IconSearch } from '@douyinfe/semi-icons';
import { get } from '../api/client';
import type { Story, StoryMember } from '../types';
import { PageHeader } from '../components/PageHeader';
import { StatePanel } from '../components/StatePanel';

type Detail={story:Story;timeline:StoryMember[];interactions:unknown[]};
export function StoryPage(){const {id}=useParams(),navigate=useNavigate();const list=useQuery({queryKey:['stories'],queryFn:()=>get<Story[]>('/stories?limit=100'),enabled:!id});const detail=useQuery({queryKey:['story',id],queryFn:()=>get<Detail>(`/stories/${id}`),enabled:!!id});if(id)return <StatePanel loading={detail.isLoading} error={detail.error}><PageHeader eyebrow="STORY TIMELINE" title={detail.data?.story.title??'事件'} description="将官方发布、媒体分析与社区线索放回同一事件脉络，同时保留其来源角色。" actions={<Button theme="solid" icon={<IconSearch/>} onClick={()=>navigate(`/research?story=${id}&q=${encodeURIComponent(detail.data?.story.title??'')}`)}>启动研究</Button>}/><div className="detail-grid"><Card title="事件脉络" className="panel-card"><Timeline>{detail.data?.timeline.map(m=><Timeline.Item key={m.documentVersionId} time={new Date(m.addedAt).toLocaleString()} type={m.role==='PRIMARY'?'success':'default'}><strong>{m.role==='PRIMARY'?'一级来源':'相关报道'}</strong><p>{m.sourceFamily}</p><small>聚类相似度 {Math.round(m.similarity*100)}%</small></Timeline.Item>)}</Timeline></Card><Card title="情报画像" className="panel-card"><div className="metric-list"><div><span>来源</span><b>{detail.data?.story.sourceCount}</b></div><div><span>独立来源族</span><b>{detail.data?.story.sourceFamilyCount}</b></div><div><span>人工覆盖</span><b>{detail.data?.story.manualOverride?'是':'否'}</b></div></div><h4>实体</h4>{detail.data?.story.entities.map(v=><Tag key={v}>{v}</Tag>)}<h4>主题</h4>{detail.data?.story.topics.map(v=><Tag color="blue" key={v}>{v}</Tag>)}</Card></div></StatePanel>;return <><PageHeader eyebrow="STORY GRAPH" title="事件" description="去重后的事件集合，而不是重复新闻列表。"/><StatePanel loading={list.isLoading} error={list.error} empty={!list.data?.length}><List className="list-panel" dataSource={list.data} renderItem={story=><List.Item onClick={()=>navigate(`/stories/${story.id}`)} main={<div><h3>{story.title}</h3><p>{story.summary||'等待摘要增强'}</p></div>} extra={<div><Tag>{story.sourceFamilyCount} 来源族</Tag><span>{new Date(story.lastObservedAt).toLocaleDateString()}</span></div>}/>} /></StatePanel></>}

