import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Input, Modal, Select, Tag, Toast } from '@douyinfe/semi-ui';
import { IconPlus } from '@douyinfe/semi-icons';
import { get, post } from '../api/client';
import type { ChangeEvent, WatchTarget } from '../types';
import { PageHeader } from '../components/PageHeader';
import { StatePanel } from '../components/StatePanel';

export function WatchlistPage(){const client=useQueryClient();const [modal,setModal]=useState(false),[name,setName]=useState(''),[expression,setExpression]=useState(''),[type,setType]=useState('ENTITY'),[selected,setSelected]=useState<string>();const watches=useQuery({queryKey:['watchlists'],queryFn:()=>get<WatchTarget[]>('/watchlists')});const changes=useQuery({queryKey:['changes',selected],queryFn:()=>get<ChangeEvent[]>(`/watchlists/${selected}/changes`),enabled:!!selected});const create=useMutation({mutationFn:()=>post('/watchlists',{type,name,expression,baseline:{}}),onSuccess:()=>{client.invalidateQueries({queryKey:['watchlists']});setModal(false);Toast.success('已建立基线跟踪')}});return <><PageHeader eyebrow="CONTINUOUS WATCH" title="跟踪" description="基线、变化检测、提醒与增量研究组成持续闭环。" actions={<Button theme="solid" icon={<IconPlus/>} onClick={()=>setModal(true)}>新增跟踪</Button>}/><StatePanel loading={watches.isLoading} error={watches.error} empty={!watches.data?.length}><div className="watch-layout"><div className="watch-list">{watches.data?.map(w=><div key={w.id} onClick={()=>setSelected(w.id)}><Card className={`watch-card ${selected===w.id?'selected':''}`}><div><Tag color="blue">{w.type}</Tag><Tag>{w.enabled?'运行中':'已暂停'}</Tag></div><h3>{w.name}</h3><p>{w.expression}</p><small>基线 v{w.baselineVersion} · {new Date(w.updatedAt).toLocaleString()}</small></Card></div>)}</div><Card className="changes-panel" title="变化时间线">{!selected?<p className="muted">选择一个跟踪目标查看变化</p>:changes.data?.length?changes.data.map(c=><div className="change-item" key={c.id}><div><Tag color={c.severity==='HIGH'||c.severity==='CRITICAL'?'red':'orange'}>{c.severity}</Tag><b>{c.field}</b><span>{new Date(c.detectedAt).toLocaleString()}</span></div><p><del>{c.oldValue??'未设置'}</del><strong>→</strong><ins>{c.newValue??'已移除'}</ins></p><small>{c.source} · {c.rule} · 置信度 {Math.round(c.confidence*100)}%</small></div>):<p className="ok-copy">基线稳定，尚未发现变化</p>}</Card></div></StatePanel><Modal title="新增跟踪目标" visible={modal} onCancel={()=>setModal(false)} onOk={()=>create.mutate()}><label className="field-label">类型</label><Select value={type} onChange={v=>setType(String(v))} optionList={['ENTITY','TOPIC','QUERY','CLAIM','COMPARISON_SET'].map(v=>({label:v,value:v}))} style={{width:'100%'}}/><label className="field-label">名称</label><Input value={name} onChange={setName}/><label className="field-label">跟踪表达式</label><Input value={expression} onChange={setExpression}/></Modal></>}
